/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUserSettingsRouteImport } from './routes/app.user-settings'
import { Route as AppSourcesRouteImport } from './routes/app.sources'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppMaterialsRouteImport } from './routes/app.materials'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppBillsOfMaterialsRouteImport } from './routes/app.bills-of-materials'
import { Route as AppSourcesIndexRouteImport } from './routes/app.sources.index'
import { Route as AppProductsIndexRouteImport } from './routes/app.products.index'
import { Route as AppSourcesNewRouteImport } from './routes/app.sources.new'
import { Route as AppSourcesSourceIdRouteImport } from './routes/app.sources.$sourceId'
import { Route as AppProductsProductIdRouteImport } from './routes/app.products.$productId'
import { Route as AppSourcesSourceIdEditRouteImport } from './routes/app.sources.$sourceId_.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUserSettingsRoute = AppUserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsOfMaterialsRoute = AppBillsOfMaterialsRouteImport.update({
  id: '/bills-of-materials',
  path: '/bills-of-materials',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIndexRoute = AppSourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSourcesRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppSourcesNewRoute = AppSourcesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSourcesRoute,
} as any)
const AppSourcesSourceIdRoute = AppSourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => AppSourcesRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppSourcesSourceIdEditRoute = AppSourcesSourceIdEditRouteImport.update({
  id: '/$sourceId_/edit',
  path: '/$sourceId/edit',
  getParentRoute: () => AppSourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/bills-of-materials': typeof AppBillsOfMaterialsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/sources': typeof AppSourcesRouteWithChildren
  '/app/user-settings': typeof AppUserSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/sources/$sourceId': typeof AppSourcesSourceIdRoute
  '/app/sources/new': typeof AppSourcesNewRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/sources/': typeof AppSourcesIndexRoute
  '/app/sources/$sourceId/edit': typeof AppSourcesSourceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/bills-of-materials': typeof AppBillsOfMaterialsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/user-settings': typeof AppUserSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/sources/$sourceId': typeof AppSourcesSourceIdRoute
  '/app/sources/new': typeof AppSourcesNewRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/sources': typeof AppSourcesIndexRoute
  '/app/sources/$sourceId/edit': typeof AppSourcesSourceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/bills-of-materials': typeof AppBillsOfMaterialsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/sources': typeof AppSourcesRouteWithChildren
  '/app/user-settings': typeof AppUserSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/sources/$sourceId': typeof AppSourcesSourceIdRoute
  '/app/sources/new': typeof AppSourcesNewRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/sources/': typeof AppSourcesIndexRoute
  '/app/sources/$sourceId_/edit': typeof AppSourcesSourceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/bills-of-materials'
    | '/app/inventory'
    | '/app/materials'
    | '/app/products'
    | '/app/sources'
    | '/app/user-settings'
    | '/app/'
    | '/app/products/$productId'
    | '/app/sources/$sourceId'
    | '/app/sources/new'
    | '/app/products/'
    | '/app/sources/'
    | '/app/sources/$sourceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/bills-of-materials'
    | '/app/inventory'
    | '/app/materials'
    | '/app/user-settings'
    | '/app'
    | '/app/products/$productId'
    | '/app/sources/$sourceId'
    | '/app/sources/new'
    | '/app/products'
    | '/app/sources'
    | '/app/sources/$sourceId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/bills-of-materials'
    | '/app/inventory'
    | '/app/materials'
    | '/app/products'
    | '/app/sources'
    | '/app/user-settings'
    | '/app/'
    | '/app/products/$productId'
    | '/app/sources/$sourceId'
    | '/app/sources/new'
    | '/app/products/'
    | '/app/sources/'
    | '/app/sources/$sourceId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/user-settings': {
      id: '/app/user-settings'
      path: '/user-settings'
      fullPath: '/app/user-settings'
      preLoaderRoute: typeof AppUserSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sources': {
      id: '/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materials': {
      id: '/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills-of-materials': {
      id: '/app/bills-of-materials'
      path: '/bills-of-materials'
      fullPath: '/app/bills-of-materials'
      preLoaderRoute: typeof AppBillsOfMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sources/': {
      id: '/app/sources/'
      path: '/'
      fullPath: '/app/sources/'
      preLoaderRoute: typeof AppSourcesIndexRouteImport
      parentRoute: typeof AppSourcesRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/sources/new': {
      id: '/app/sources/new'
      path: '/new'
      fullPath: '/app/sources/new'
      preLoaderRoute: typeof AppSourcesNewRouteImport
      parentRoute: typeof AppSourcesRoute
    }
    '/app/sources/$sourceId': {
      id: '/app/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/app/sources/$sourceId'
      preLoaderRoute: typeof AppSourcesSourceIdRouteImport
      parentRoute: typeof AppSourcesRoute
    }
    '/app/products/$productId': {
      id: '/app/products/$productId'
      path: '/$productId'
      fullPath: '/app/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/sources/$sourceId_/edit': {
      id: '/app/sources/$sourceId_/edit'
      path: '/$sourceId/edit'
      fullPath: '/app/sources/$sourceId/edit'
      preLoaderRoute: typeof AppSourcesSourceIdEditRouteImport
      parentRoute: typeof AppSourcesRoute
    }
  }
}

interface AppProductsRouteChildren {
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppSourcesRouteChildren {
  AppSourcesSourceIdRoute: typeof AppSourcesSourceIdRoute
  AppSourcesNewRoute: typeof AppSourcesNewRoute
  AppSourcesIndexRoute: typeof AppSourcesIndexRoute
  AppSourcesSourceIdEditRoute: typeof AppSourcesSourceIdEditRoute
}

const AppSourcesRouteChildren: AppSourcesRouteChildren = {
  AppSourcesSourceIdRoute: AppSourcesSourceIdRoute,
  AppSourcesNewRoute: AppSourcesNewRoute,
  AppSourcesIndexRoute: AppSourcesIndexRoute,
  AppSourcesSourceIdEditRoute: AppSourcesSourceIdEditRoute,
}

const AppSourcesRouteWithChildren = AppSourcesRoute._addFileChildren(
  AppSourcesRouteChildren,
)

interface AppRouteChildren {
  AppBillsOfMaterialsRoute: typeof AppBillsOfMaterialsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppSourcesRoute: typeof AppSourcesRouteWithChildren
  AppUserSettingsRoute: typeof AppUserSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsOfMaterialsRoute: AppBillsOfMaterialsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppSourcesRoute: AppSourcesRouteWithChildren,
  AppUserSettingsRoute: AppUserSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
