/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUserSettingsRouteImport } from './routes/app.user-settings'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppMaterialsRouteImport } from './routes/app.materials'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppBillsOfMaterialsRouteImport } from './routes/app.bills-of-materials'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUserSettingsRoute = AppUserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsOfMaterialsRoute = AppBillsOfMaterialsRouteImport.update({
  id: '/bills-of-materials',
  path: '/bills-of-materials',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/bills-of-materials': typeof AppBillsOfMaterialsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/products': typeof AppProductsRoute
  '/app/user-settings': typeof AppUserSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/bills-of-materials': typeof AppBillsOfMaterialsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/products': typeof AppProductsRoute
  '/app/user-settings': typeof AppUserSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/bills-of-materials': typeof AppBillsOfMaterialsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/products': typeof AppProductsRoute
  '/app/user-settings': typeof AppUserSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/bills-of-materials'
    | '/app/inventory'
    | '/app/materials'
    | '/app/products'
    | '/app/user-settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/bills-of-materials'
    | '/app/inventory'
    | '/app/materials'
    | '/app/products'
    | '/app/user-settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/bills-of-materials'
    | '/app/inventory'
    | '/app/materials'
    | '/app/products'
    | '/app/user-settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/user-settings': {
      id: '/app/user-settings'
      path: '/user-settings'
      fullPath: '/app/user-settings'
      preLoaderRoute: typeof AppUserSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materials': {
      id: '/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills-of-materials': {
      id: '/app/bills-of-materials'
      path: '/bills-of-materials'
      fullPath: '/app/bills-of-materials'
      preLoaderRoute: typeof AppBillsOfMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillsOfMaterialsRoute: typeof AppBillsOfMaterialsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppUserSettingsRoute: typeof AppUserSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsOfMaterialsRoute: AppBillsOfMaterialsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppProductsRoute: AppProductsRoute,
  AppUserSettingsRoute: AppUserSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
