/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'revokedAt', 'updatedAt', 'userId'] as const
  $columns = AccessTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class CollectionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = CollectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LoginAttemptSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'failureCount', 'id', 'lockedUntil', 'updatedAt'] as const
  $columns = LoginAttemptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare failureCount: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaterialSourceLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isPreferred', 'materialId', 'materialSourceId', 'sortOrder', 'updatedAt'] as const
  $columns = MaterialSourceLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPreferred: boolean
  @column()
  declare materialId: number
  @column()
  declare materialSourceId: number
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaterialSourceSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'legacySourceId', 'name', 'normalizedUnit', 'normalizedUnitCostCents', 'provider', 'publicId', 'purchaseUnit', 'textileFamily', 'updatedAt'] as const
  $columns = MaterialSourceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare legacySourceId: string
  @column()
  declare name: string
  @column()
  declare normalizedUnit: string
  @column()
  declare normalizedUnitCostCents: number
  @column()
  declare provider: string
  @column()
  declare publicId: string
  @column()
  declare purchaseUnit: string
  @column()
  declare textileFamily: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaterialSchema extends BaseModel {
  static $columns = ['comments', 'createdAt', 'deletedAt', 'id', 'legacyMaterialId', 'materialColor', 'materialUnit', 'materialUse', 'name', 'publicId', 'updatedAt'] as const
  $columns = MaterialSchema.$columns
  @column()
  declare comments: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare legacyMaterialId: string
  @column()
  declare materialColor: string
  @column()
  declare materialUnit: string
  @column()
  declare materialUse: string
  @column()
  declare name: string
  @column()
  declare publicId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductSchema extends BaseModel {
  static $columns = ['collectionId', 'createdAt', 'createdByUserId', 'deletedAt', 'id', 'lifecycleStatus', 'name', 'productCategory', 'productImageFileName', 'productImageStorageKey', 'productStatus', 'publicId', 'shortDescription', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare collectionId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lifecycleStatus: string
  @column()
  declare name: string
  @column()
  declare productCategory: string | null
  @column()
  declare productImageFileName: string | null
  @column()
  declare productImageStorageKey: string | null
  @column()
  declare productStatus: string
  @column()
  declare publicId: string
  @column()
  declare shortDescription: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'email', 'id', 'passwordHash', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare passwordHash: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
